version: '3'

services:  

    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: agenda_db
        env_file: .env
        environment:
            - MYSQL_HOST=db
        ports:
            - "3307:3306"
        volumes:
            - db_data:/data/db
            - ./agenda.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
    api:
        image: agenda_api
        container_name: agenda_api
        env_file: .env
        environment:
            - MYSQL_HOST=db
        restart: always
        volumes:
            - app:/home/node/app
        ports:
            - "9001:80"
        depends_on:  
            - db
volumes:
  db_data:
  app: